apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  ENVIRONMENT: "production"
  POSTGRES_DB: "taskflow_db"
  POSTGRES_USER: "taskflow"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  BACKEND_PORT: "8000"
