apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
  - configmap.yaml
  - postgres-deployment.yaml
  - migration-job.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
