apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskflow-backend-kustomize
  namespace: taskflow
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskflow
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
